if(NOT DEFINED VALIDATOR)
    message(FATAL_ERROR "VALIDATOR is required")
endif()

set(BinanceMarketDataContracts_SCHEMA_BASELINE
    "01d76a41929f36d89573159f5f458f9f1e378ada")
set(BinanceMarketDataContracts_SCHEMA_FINGERPRINT
    "33286fb1d624f4dd0c827010e93113f523c7f37dc4f6ae526361d2b0c61626c0")
set(BinanceMarketDataContracts_SCHEMA_FINGERPRINT_ALGORITHM_VERSION "1")
set(BinanceMarketDataContracts_PACKAGE_VERSION "0.1.0")
set(BinanceMarketDataContracts_PACKAGE_REVISION "NOT_FORMALLY_ASSIGNED")
set(BinanceMarketDataContracts_PROTOC_VERSION "libprotoc 33.5")
set(BinanceMarketDataContracts_CPP_GENERATOR_OPTIONS
    "cpp_out=dllexport_decl=BMD_CONTRACTS_PROTOBUF_API")
set(BinanceMarketDataContracts_PROTOBUF_RUNTIME_VERSION "6.33.5")
set(BinanceMarketDataContracts_PROTOBUF_RUNTIME_RREV
    "ca5ff466767b31a1b496ec60247e105c")
set(BinanceMarketDataContracts_PROTOBUF_RUNTIME_COMPATIBILITY
    "exactly 6.33.5 for this implementation candidate")
set(BinanceMarketDataContracts_PROTOBUF_RUNTIME_FLAVOR "full")
set(BinanceMarketDataContracts_PROTOBUF_RUNTIME_LINKAGE "static")
set(BinanceMarketDataContracts_CONTRACTS_SOURCE_REVISION
    "67ee1bf69fad980d114cfa278c3a6ffe310a4d7a")

if(CASE STREQUAL "baseline")
    set(BinanceMarketDataContracts_SCHEMA_BASELINE wrong)
elseif(CASE STREQUAL "fingerprint")
    set(BinanceMarketDataContracts_SCHEMA_FINGERPRINT wrong)
elseif(CASE STREQUAL "algorithm")
    set(BinanceMarketDataContracts_SCHEMA_FINGERPRINT_ALGORITHM_VERSION 2)
elseif(CASE STREQUAL "source")
    set(BinanceMarketDataContracts_CONTRACTS_SOURCE_REVISION wrong)
elseif(CASE STREQUAL "package_version")
    set(BinanceMarketDataContracts_PACKAGE_VERSION 0.2.0)
elseif(CASE STREQUAL "package_revision")
    set(BinanceMarketDataContracts_PACKAGE_REVISION 67ee1bf)
elseif(CASE STREQUAL "protoc")
    set(BinanceMarketDataContracts_PROTOC_VERSION wrong)
elseif(CASE STREQUAL "runtime")
    set(BinanceMarketDataContracts_PROTOBUF_RUNTIME_VERSION wrong)
elseif(CASE STREQUAL "rrev")
    set(BinanceMarketDataContracts_PROTOBUF_RUNTIME_RREV wrong)
elseif(CASE STREQUAL "flavor")
    set(BinanceMarketDataContracts_PROTOBUF_RUNTIME_FLAVOR lite)
elseif(CASE STREQUAL "linkage")
    set(BinanceMarketDataContracts_PROTOBUF_RUNTIME_LINKAGE unknown)
elseif(CASE STREQUAL "missing")
    unset(BinanceMarketDataContracts_SCHEMA_FINGERPRINT)
elseif(NOT CASE STREQUAL "valid")
    message(FATAL_ERROR "unknown metadata case: ${CASE}")
endif()

include("${VALIDATOR}")
bmd_projection_validate_contracts_metadata()
