#!/usr/bin/env bash
# quality.sh — canonical Quality entrypoint (INFRA-TC-001).
#
# ONE repository-owned command for authoritative Quality acceptance. CI and
# local developers must call this same entrypoint; it must not be redefined
# in the workflow.
#
# Host branch:
#   - validates the toolchain contract file (.toolchain/quality.env)
#   - rejects test-only environment hooks (BMD_QUALITY_*) and stale internal
#     orchestration variables (BMD_CANONICAL_QUALITY_*): canonical acceptance
#     must never validate one contract/time identity and execute another, and
#     ambient environment can never select the container execution mode or
#     substitute the source/work roots
#   - requires a REAL Docker Engine backend (Docker Engine on Linux, Docker
#     Desktop on macOS; Podman/podman-docker is NOT a validated canonical
#     acceptance runtime)
#   - builds the canonical image from the pinned base digest and exact
#     package pins in the contract (fail closed if apt cannot install the
#     exact versions)
#   - runs the container, mounting this working tree read-only
#
# Internal mode (--inside-canonical-container, entered ONLY through the
# explicit argument generated by the trusted host path; never by ambient
# environment):
#   0. proves the canonical image boundary: the image-baked contract
#      (/opt/toolchain/quality.env) exists and equals the mounted /src
#      contract, BEFORE any source copy or recursive execution
#   1. copies the mounted source into the fixed canonical scratch root /work
#      (fresh copy per run; the host working tree is never polluted; /src and
#      /work are fixed and not ambient-substitutable)
#   2. re-verifies the image boundary on the /work scratch tree
#   3. fails closed unless the running toolchain matches the contract
#   4. runs the exact Quality semantics: formatting, repository-local Conan
#      bootstrap, pinned Contracts bootstrap, Debug configure with
#      ProtoAdapter ON, clang-tidy ON, Werror ON, build, tests, and the
#      staged-install consumer
#
# Persistent caches (.cache, .venv-tools) are namespaced by the canonical
# cache key (scripts/quality-cache-key.sh) and mounted as named volumes by
# the host branch; /work itself is ephemeral per run and build outputs never
# persist, so no lifecycle-sensitive fingerprint file is needed.
#
# Local reproduction: bash scripts/quality.sh
#   macOS: Docker Desktop (amd64 containers run through Rosetta 2).
#   Linux: Docker Engine.
# Podman is NOT a validated canonical acceptance runtime; supporting it is a
# separate task requiring SELinux/rootless/runtime integration evidence.
#
# See docs/QUALITY_TOOLCHAIN.md for the contract and upgrade procedure.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# --------------------------------------------------------------------------
# Test-only hooks (BMD_QUALITY_*) and stale internal orchestration variables
# (BMD_CANONICAL_QUALITY_*) are forbidden in canonical Quality. The
# deterministic contract tests may set BMD_QUALITY_* when invoking the
# checker directly; the canonical entrypoint must FAIL CLOSED before any
# image construction if an ambient developer/CI environment tries to redefine
# the authoritative contract path, the reference UTC time, the fake tool
# tree, the fake dpkg metadata directory, the container execution mode, or
# the source/work roots.
# --------------------------------------------------------------------------
for hook in \
    BMD_QUALITY_CONTRACT_FILE \
    BMD_QUALITY_REFERENCE_TIME \
    BMD_QUALITY_TOOLCHAIN_DIR \
    BMD_QUALITY_DPKG_INFO_DIR \
    BMD_QUALITY_WORK_KEEP \
    BMD_CANONICAL_QUALITY_CONTAINER \
    BMD_CANONICAL_QUALITY_SRC \
    BMD_CANONICAL_QUALITY_WORK; do
    if [[ -n "${!hook:-}" ]]; then
        echo "QUALITY FAIL: forbidden variable ${hook} is set in the environment" >&2
        echo "QUALITY FAIL: canonical Quality must not be influenced by test hooks or stale internal orchestration variables" >&2
        echo "QUALITY FAIL: unset ${hook} and retry (authoritative contract: ${repo_root}/.toolchain/quality.env; reference time: real UTC clock)" >&2
        exit 1
    fi
done

mode="host"
case "${1:-}" in
    "") ;;
    --inside-canonical-container) mode="inside-canonical-container" ;;
    *)
        echo "usage: $0 [--inside-canonical-container]" >&2
        echo "  (no arguments: canonical HOST mode; --inside-canonical-container is an internal mode" >&2
        echo "   entered only by the trusted host path inside the canonical image)" >&2
        exit 2
        ;;
esac

if [[ "$mode" == "inside-canonical-container" ]]; then
    # ------------------------------------------------------------------
    # Internal mode (inside the canonical image only)
    #
    # Source and work roots are FIXED (/src and /work); they are not
    # ambient-substitutable. Before any source copy, recursive execution,
    # toolchain acceptance, or PASS output, the canonical image boundary
    # must be proven.
    # ------------------------------------------------------------------
    src="/src"
    work="/work"

    if [[ "$(pwd)" != "$work" ]]; then
        echo "Canonical Quality: proving canonical image boundary"
        "$repo_root/scripts/quality-image-boundary.sh" /opt/toolchain/quality.env "$src"
        [[ "$(pwd)" == "$src" ]] || {
            echo "QUALITY FAIL: internal mode must be entered from the canonical image layout (${src})" >&2
            exit 1
        }
        echo "Canonical Quality: preparing canonical scratch root"
        "$repo_root/scripts/quality-work-prep.sh" "$src" "$work"
        cd "$work"
        exec bash scripts/quality.sh --inside-canonical-container
    fi

    cd "$work"
    echo "Canonical Quality: re-proving canonical image boundary on the scratch tree"
    "$repo_root/scripts/quality-image-boundary.sh" /opt/toolchain/quality.env "$work"

    set -a
    # shellcheck disable=SC1091
    . .toolchain/quality.env
    set +a

    echo "Canonical Quality toolchain identity:"
    echo "  clang/clang++/clang-tidy/clang-format $LLVM_MAJOR.$LLVM_MINOR.$LLVM_PATCH"
    echo "  $CANONICAL_QUALITY_OS $CANONICAL_QUALITY_ARCH"
    echo "  base $CANONICAL_QUALITY_BASE_IMAGE $CANONICAL_QUALITY_BASE_IMAGE_DIGEST"
    echo "  ubuntu snapshot $UBUNTU_SNAPSHOT_ID"
    echo "  C++ standard $CPP_STANDARD"

    scripts/quality-toolchain-check.sh --skip-conan

    echo "Canonical Quality: formatting check"
    find include src tests benchmarks fuzz -type f \( -name '*.cpp' -o -name '*.hpp' \) -print0 \
        | xargs -0 clang-format --dry-run --Werror

    export CC=clang
    export CXX=clang++

    echo "Canonical Quality: repository-local Conan bootstrap"
    scripts/bootstrap.sh

    export PATH="$work/.venv-tools/bin:$PATH"
    scripts/quality-toolchain-check.sh

    echo "Canonical Quality: pinned Contracts bootstrap"
    scripts/bootstrap-contracts.sh

    echo "Canonical Quality: configure (Debug, ProtoAdapter ON, clang-tidy ON, Werror ON)"
    scripts/configure.sh debug \
        -DBMD_PROJECTION_BUILD_PROTO_ADAPTER=ON \
        -DBMD_PROJECTION_ENABLE_CLANG_TIDY=ON \
        -DBMD_PROJECTION_ENABLE_WERROR=ON

    echo "Canonical Quality: build"
    scripts/build.sh debug

    echo "Canonical Quality: tests"
    scripts/test.sh debug

    echo "Canonical Quality: staged install consumer"
    scripts/install-consumer-test.sh

    echo "CANONICAL QUALITY: PASS (clang/clang++/clang-tidy/clang-format $LLVM_MAJOR.$LLVM_MINOR.$LLVM_PATCH, $CANONICAL_QUALITY_OS $CANONICAL_QUALITY_ARCH, snapshot $UBUNTU_SNAPSHOT_ID)"
    exit 0
fi

# ------------------------------------------------------------------
# Host branch
# ------------------------------------------------------------------
cd "$repo_root"

echo "Canonical Quality: validating toolchain contract"
scripts/quality-toolchain-check.sh --contract-only

base_ref="$(bash scripts/quality-base-ref.sh)"
snapshot_id="$(sed -n 's/^UBUNTU_SNAPSHOT_ID=//p' .toolchain/quality.env | head -n1)"
echo "Canonical Quality: base reference $base_ref"
echo "Canonical Quality: ubuntu snapshot $snapshot_id"

runtime=""
if scripts/quality-runtime-check.sh; then
    runtime="docker"
else
    exit 1
fi

if [[ "$(uname -m)" != "x86_64" ]]; then
    echo "Note: host architecture is $(uname -m); canonical Quality runs the pinned"
    echo "      amd64 container (Docker Desktop on Apple Silicon uses Rosetta 2)."
fi

sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256
    else
        echo "no sha256 tool found" >&2
        exit 1
    fi
}
image_tag="bmd-projection-quality:$(grep -vE '^[[:space:]]*(#|$)' .toolchain/quality.env | sha256_of | cut -c1-16)"

echo "Canonical Quality: building pinned toolchain image ($runtime)"
"$runtime" build --platform linux/amd64 \
    --build-arg "BMD_CANONICAL_BASE_IMAGE_REF=$base_ref" \
    -t "$image_tag" -f .toolchain/Dockerfile .

echo "Canonical Quality: running canonical acceptance in the pinned container"
cache_key="$(bash scripts/quality-cache-key.sh)"
cache_volume="bmd-projection-quality-cache-${cache_key}"
venv_volume="bmd-projection-quality-venv-${cache_key}"
echo "Canonical Quality: cache namespace ${cache_key}"
echo "Canonical Quality: persistent volumes ${cache_volume} / ${venv_volume} (dependency caches only; /work is ephemeral)"
"$runtime" run --rm --platform linux/amd64 \
    -v "$repo_root":/src:ro \
    -v "$cache_volume":/work/.cache \
    -v "$venv_volume":/work/.venv-tools \
    -w /src \
    "$image_tag" \
    bash scripts/quality.sh --inside-canonical-container
